name: Bug report
description: Report a reproducible problem in path2map.
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please include enough detail for maintainers to reproduce and fix it.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: A short, clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands and setup used.
      placeholder: |
        1. Run ...
        2. Use flags ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened, including errors/output.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Python version, OS, and path2map version.
      placeholder: |
        path2map version:
        python version:
        os:
    validations:
      required: true
